Work around https://github.com/google/guava/issues/7397
which results in

> Task :android:app:full:minifyReleaseWithR8
ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /home/runner/work/net.twisterrob.travel/net.twisterrob.travel/android/app/full/build/outputs/mapping/release/missing_rules.txt.
ERROR: R8: Missing class com.google.j2objc.annotations.ReflectionSupport (referenced from: com.google.common.util.concurrent.AbstractFuture)
Missing class com.google.j2objc.annotations.RetainedWith (referenced from: com.google.common.collect.ImmutableSet com.google.common.collect.ImmutableMap.entrySet and 3 other contexts)

because places 4.1.0 added guava 33.3.0 dep